name: logan
channels:
- defaults
dependencies:
- certifi=2016.2.28=py35_0
- pip=9.0.1=py35_1
- python=3.5.4=0
- setuptools=36.4.0=py35_1
- vc=14=0
- vs2015_runtime=14.0.25420=0
- wheel=0.29.0=py35_0
- wincertstore=0.2=py35_0
- pip:
  - cycler==0.10.0
  - gast==0.2.0
  - kiwisolver==1.0.1
  - matplotlib==2.2.2
  - numpy==1.14.0
  - opencv-contrib-python==3.4.1.15
  - pandas==0.23.1
  - pillow==5.1.0
  - pyparsing==2.2.0
  - python-dateutil==2.7.3
  - pytz==2018.4
  - scikit-learn==0.19.1
  - six==1.11.0
  - webcolors==1.8.1
prefix: C:\Users\ami\AppData\Local\conda\conda\envs\logan

